---
deployment:
  tasks:
    - cd /home/USERNAME/temanbelajarkaifa && $(bash scripts/find-php.sh) artisan migrate --force
    - cd /home/USERNAME/temanbelajarkaifa && $(bash scripts/find-php.sh) artisan optimize:clear
    - cd /home/USERNAME/temanbelajarkaifa && $(bash scripts/find-php.sh) artisan optimize
